### ISSUE TITLE
defaultSchema uses VARCHAR for value

### ISSUE THREAD

**Issue by chanphillip** [yonjah/node_acl_sequelize#9]
Got problems after using this for awhile when we have more users created. The user list in acl_meta table got full with VARCHAR(255)
```
value: {type: db.Sequelize.STRING}
```
Then I found that you can overwrite the options when initializing AclSeq which can solve my problem, but I think it would be great to change the default one.

**Comment by yonjah** [comment]
@chanphillip  Thanks for this report.

This is actually a known issue and mentioned in the readme.
The reason for not choosing anything higher by default is that it might impact performance.

The real issue is that the schema being used is just naive clone of the original backend provided with node_acl. A much more better schema will be one that uses relations between resources and will not have any limit on the amount of objects that can be used.

Unfortunately this requires a bit of work and I'm not sure when I'll have the time to do this change

**Comment by milesalex** [comment]
Just ran into this too... Maybe lay out a plan for improving this and request a PR?

**Comment by yonjah** [comment]
@milesalex PRs are always welcome though this project needs a lot of work.
Let me know what other info you think you might need if you plan to work on this

**Comment by yonjah** [comment]
Closing this issue sue lack of activity.
Feel free to reopen if you are still affected by it
